/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as V1ProfileRouteImport } from './routes/v1/profile'
import { Route as V1OpenapiDotjsonRouteImport } from './routes/v1/openapi[.]json'
import { Route as V1ImportsRouteImport } from './routes/v1/imports'
import { Route as V1HealthRouteImport } from './routes/v1/health'
import { Route as V1ExportsRouteImport } from './routes/v1/exports'
import { Route as V1BeliefsRouteImport } from './routes/v1/beliefs'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardSourcesRouteImport } from './routes/dashboard.sources'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard.playground'
import { Route as DashboardOperationsRouteImport } from './routes/dashboard.operations'
import { Route as DashboardMemoriesRouteImport } from './routes/dashboard.memories'
import { Route as DashboardEntitiesRouteImport } from './routes/dashboard.entities'
import { Route as DashboardCreateApiRouteImport } from './routes/dashboard.create-api'
import { Route as DashboardConfigurationRouteImport } from './routes/dashboard.configuration'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as V1StateIndexRouteImport } from './routes/v1/state/index'
import { Route as V1OperationsIndexRouteImport } from './routes/v1/operations/index'
import { Route as V1MemoriesIndexRouteImport } from './routes/v1/memories/index'
import { Route as V1EventsIndexRouteImport } from './routes/v1/events/index'
import { Route as V1EntitiesIndexRouteImport } from './routes/v1/entities/index'
import { Route as V1DocumentsIndexRouteImport } from './routes/v1/documents/index'
import { Route as V1DocumentUploadsIndexRouteImport } from './routes/v1/document-uploads/index'
import { Route as V1StateHistoryRouteImport } from './routes/v1/state/history'
import { Route as V1OperationsIdRouteImport } from './routes/v1/operations/$id'
import { Route as V1MemoriesSearchRouteImport } from './routes/v1/memories/search'
import { Route as V1MemoriesBatchRouteImport } from './routes/v1/memories/batch'
import { Route as V1MemoriesIdRouteImport } from './routes/v1/memories/$id'
import { Route as V1EventsIdRouteImport } from './routes/v1/events/$id'
import { Route as V1DocumentsSearchRouteImport } from './routes/v1/documents/search'
import { Route as V1DocumentsIdRouteImport } from './routes/v1/documents/$id'
import { Route as V1DocumentUploadsIdRouteImport } from './routes/v1/document-uploads/$id'
import { Route as DashboardEntitiesIdRouteImport } from './routes/dashboard.entities.$id'
import { Route as ApiGoogleAuthStartRouteImport } from './routes/api/google-auth/start'
import { Route as ApiGithubAuthStartRouteImport } from './routes/api/github-auth/start'
import { Route as ApiCronTasksRouteImport } from './routes/api/cron/tasks'
import { Route as ApiCronMaintenanceRouteImport } from './routes/api/cron/maintenance'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAppSplatRouteImport } from './routes/api/app/$'
import { Route as V1OperationsIdRetryRouteImport } from './routes/v1/operations/$id/retry'
import { Route as V1MemoriesIdHistoryRouteImport } from './routes/v1/memories/$id/history'
import { Route as V1MemoriesIdFeedbackRouteImport } from './routes/v1/memories/$id/feedback'
import { Route as V1EntitiesTypeIdRouteImport } from './routes/v1/entities/$type/$id'
import { Route as V1DocumentsIdContentRouteImport } from './routes/v1/documents/$id/content'
import { Route as V1DocumentUploadsIdContentRouteImport } from './routes/v1/document-uploads/$id/content'
import { Route as V1DocumentUploadsIdCompleteRouteImport } from './routes/v1/document-uploads/$id/complete'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const V1ProfileRoute = V1ProfileRouteImport.update({
  id: '/v1/profile',
  path: '/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const V1OpenapiDotjsonRoute = V1OpenapiDotjsonRouteImport.update({
  id: '/v1/openapi.json',
  path: '/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ImportsRoute = V1ImportsRouteImport.update({
  id: '/v1/imports',
  path: '/v1/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const V1HealthRoute = V1HealthRouteImport.update({
  id: '/v1/health',
  path: '/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ExportsRoute = V1ExportsRouteImport.update({
  id: '/v1/exports',
  path: '/v1/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BeliefsRoute = V1BeliefsRouteImport.update({
  id: '/v1/beliefs',
  path: '/v1/beliefs',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoriesRoute = DashboardMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEntitiesRoute = DashboardEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateApiRoute = DashboardCreateApiRouteImport.update({
  id: '/create-api',
  path: '/create-api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigurationRoute = DashboardConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const V1StateIndexRoute = V1StateIndexRouteImport.update({
  id: '/v1/state/',
  path: '/v1/state/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1OperationsIndexRoute = V1OperationsIndexRouteImport.update({
  id: '/v1/operations/',
  path: '/v1/operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemoriesIndexRoute = V1MemoriesIndexRouteImport.update({
  id: '/v1/memories/',
  path: '/v1/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1EventsIndexRoute = V1EventsIndexRouteImport.update({
  id: '/v1/events/',
  path: '/v1/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1EntitiesIndexRoute = V1EntitiesIndexRouteImport.update({
  id: '/v1/entities/',
  path: '/v1/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentsIndexRoute = V1DocumentsIndexRouteImport.update({
  id: '/v1/documents/',
  path: '/v1/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentUploadsIndexRoute = V1DocumentUploadsIndexRouteImport.update({
  id: '/v1/document-uploads/',
  path: '/v1/document-uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StateHistoryRoute = V1StateHistoryRouteImport.update({
  id: '/v1/state/history',
  path: '/v1/state/history',
  getParentRoute: () => rootRouteImport,
} as any)
const V1OperationsIdRoute = V1OperationsIdRouteImport.update({
  id: '/v1/operations/$id',
  path: '/v1/operations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemoriesSearchRoute = V1MemoriesSearchRouteImport.update({
  id: '/v1/memories/search',
  path: '/v1/memories/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemoriesBatchRoute = V1MemoriesBatchRouteImport.update({
  id: '/v1/memories/batch',
  path: '/v1/memories/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemoriesIdRoute = V1MemoriesIdRouteImport.update({
  id: '/v1/memories/$id',
  path: '/v1/memories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1EventsIdRoute = V1EventsIdRouteImport.update({
  id: '/v1/events/$id',
  path: '/v1/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentsSearchRoute = V1DocumentsSearchRouteImport.update({
  id: '/v1/documents/search',
  path: '/v1/documents/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentsIdRoute = V1DocumentsIdRouteImport.update({
  id: '/v1/documents/$id',
  path: '/v1/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentUploadsIdRoute = V1DocumentUploadsIdRouteImport.update({
  id: '/v1/document-uploads/$id',
  path: '/v1/document-uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntitiesIdRoute = DashboardEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEntitiesRoute,
} as any)
const ApiGoogleAuthStartRoute = ApiGoogleAuthStartRouteImport.update({
  id: '/api/google-auth/start',
  path: '/api/google-auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthStartRoute = ApiGithubAuthStartRouteImport.update({
  id: '/api/github-auth/start',
  path: '/api/github-auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTasksRoute = ApiCronTasksRouteImport.update({
  id: '/api/cron/tasks',
  path: '/api/cron/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMaintenanceRoute = ApiCronMaintenanceRouteImport.update({
  id: '/api/cron/maintenance',
  path: '/api/cron/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppSplatRoute = ApiAppSplatRouteImport.update({
  id: '/api/app/$',
  path: '/api/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1OperationsIdRetryRoute = V1OperationsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => V1OperationsIdRoute,
} as any)
const V1MemoriesIdHistoryRoute = V1MemoriesIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => V1MemoriesIdRoute,
} as any)
const V1MemoriesIdFeedbackRoute = V1MemoriesIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => V1MemoriesIdRoute,
} as any)
const V1EntitiesTypeIdRoute = V1EntitiesTypeIdRouteImport.update({
  id: '/v1/entities/$type/$id',
  path: '/v1/entities/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1DocumentsIdContentRoute = V1DocumentsIdContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => V1DocumentsIdRoute,
} as any)
const V1DocumentUploadsIdContentRoute =
  V1DocumentUploadsIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => V1DocumentUploadsIdRoute,
  } as any)
const V1DocumentUploadsIdCompleteRoute =
  V1DocumentUploadsIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => V1DocumentUploadsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/configuration': typeof DashboardConfigurationRoute
  '/dashboard/create-api': typeof DashboardCreateApiRoute
  '/dashboard/entities': typeof DashboardEntitiesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/v1/beliefs': typeof V1BeliefsRoute
  '/v1/exports': typeof V1ExportsRoute
  '/v1/health': typeof V1HealthRoute
  '/v1/imports': typeof V1ImportsRoute
  '/v1/openapi.json': typeof V1OpenapiDotjsonRoute
  '/v1/profile': typeof V1ProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/app/$': typeof ApiAppSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/github-auth/start': typeof ApiGithubAuthStartRoute
  '/api/google-auth/start': typeof ApiGoogleAuthStartRoute
  '/dashboard/entities/$id': typeof DashboardEntitiesIdRoute
  '/v1/document-uploads/$id': typeof V1DocumentUploadsIdRouteWithChildren
  '/v1/documents/$id': typeof V1DocumentsIdRouteWithChildren
  '/v1/documents/search': typeof V1DocumentsSearchRoute
  '/v1/events/$id': typeof V1EventsIdRoute
  '/v1/memories/$id': typeof V1MemoriesIdRouteWithChildren
  '/v1/memories/batch': typeof V1MemoriesBatchRoute
  '/v1/memories/search': typeof V1MemoriesSearchRoute
  '/v1/operations/$id': typeof V1OperationsIdRouteWithChildren
  '/v1/state/history': typeof V1StateHistoryRoute
  '/v1/document-uploads/': typeof V1DocumentUploadsIndexRoute
  '/v1/documents/': typeof V1DocumentsIndexRoute
  '/v1/entities/': typeof V1EntitiesIndexRoute
  '/v1/events/': typeof V1EventsIndexRoute
  '/v1/memories/': typeof V1MemoriesIndexRoute
  '/v1/operations/': typeof V1OperationsIndexRoute
  '/v1/state/': typeof V1StateIndexRoute
  '/v1/document-uploads/$id/complete': typeof V1DocumentUploadsIdCompleteRoute
  '/v1/document-uploads/$id/content': typeof V1DocumentUploadsIdContentRoute
  '/v1/documents/$id/content': typeof V1DocumentsIdContentRoute
  '/v1/entities/$type/$id': typeof V1EntitiesTypeIdRoute
  '/v1/memories/$id/feedback': typeof V1MemoriesIdFeedbackRoute
  '/v1/memories/$id/history': typeof V1MemoriesIdHistoryRoute
  '/v1/operations/$id/retry': typeof V1OperationsIdRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/configuration': typeof DashboardConfigurationRoute
  '/dashboard/create-api': typeof DashboardCreateApiRoute
  '/dashboard/entities': typeof DashboardEntitiesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/v1/beliefs': typeof V1BeliefsRoute
  '/v1/exports': typeof V1ExportsRoute
  '/v1/health': typeof V1HealthRoute
  '/v1/imports': typeof V1ImportsRoute
  '/v1/openapi.json': typeof V1OpenapiDotjsonRoute
  '/v1/profile': typeof V1ProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/app/$': typeof ApiAppSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/github-auth/start': typeof ApiGithubAuthStartRoute
  '/api/google-auth/start': typeof ApiGoogleAuthStartRoute
  '/dashboard/entities/$id': typeof DashboardEntitiesIdRoute
  '/v1/document-uploads/$id': typeof V1DocumentUploadsIdRouteWithChildren
  '/v1/documents/$id': typeof V1DocumentsIdRouteWithChildren
  '/v1/documents/search': typeof V1DocumentsSearchRoute
  '/v1/events/$id': typeof V1EventsIdRoute
  '/v1/memories/$id': typeof V1MemoriesIdRouteWithChildren
  '/v1/memories/batch': typeof V1MemoriesBatchRoute
  '/v1/memories/search': typeof V1MemoriesSearchRoute
  '/v1/operations/$id': typeof V1OperationsIdRouteWithChildren
  '/v1/state/history': typeof V1StateHistoryRoute
  '/v1/document-uploads': typeof V1DocumentUploadsIndexRoute
  '/v1/documents': typeof V1DocumentsIndexRoute
  '/v1/entities': typeof V1EntitiesIndexRoute
  '/v1/events': typeof V1EventsIndexRoute
  '/v1/memories': typeof V1MemoriesIndexRoute
  '/v1/operations': typeof V1OperationsIndexRoute
  '/v1/state': typeof V1StateIndexRoute
  '/v1/document-uploads/$id/complete': typeof V1DocumentUploadsIdCompleteRoute
  '/v1/document-uploads/$id/content': typeof V1DocumentUploadsIdContentRoute
  '/v1/documents/$id/content': typeof V1DocumentsIdContentRoute
  '/v1/entities/$type/$id': typeof V1EntitiesTypeIdRoute
  '/v1/memories/$id/feedback': typeof V1MemoriesIdFeedbackRoute
  '/v1/memories/$id/history': typeof V1MemoriesIdHistoryRoute
  '/v1/operations/$id/retry': typeof V1OperationsIdRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/configuration': typeof DashboardConfigurationRoute
  '/dashboard/create-api': typeof DashboardCreateApiRoute
  '/dashboard/entities': typeof DashboardEntitiesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/v1/beliefs': typeof V1BeliefsRoute
  '/v1/exports': typeof V1ExportsRoute
  '/v1/health': typeof V1HealthRoute
  '/v1/imports': typeof V1ImportsRoute
  '/v1/openapi.json': typeof V1OpenapiDotjsonRoute
  '/v1/profile': typeof V1ProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/app/$': typeof ApiAppSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/github-auth/start': typeof ApiGithubAuthStartRoute
  '/api/google-auth/start': typeof ApiGoogleAuthStartRoute
  '/dashboard/entities/$id': typeof DashboardEntitiesIdRoute
  '/v1/document-uploads/$id': typeof V1DocumentUploadsIdRouteWithChildren
  '/v1/documents/$id': typeof V1DocumentsIdRouteWithChildren
  '/v1/documents/search': typeof V1DocumentsSearchRoute
  '/v1/events/$id': typeof V1EventsIdRoute
  '/v1/memories/$id': typeof V1MemoriesIdRouteWithChildren
  '/v1/memories/batch': typeof V1MemoriesBatchRoute
  '/v1/memories/search': typeof V1MemoriesSearchRoute
  '/v1/operations/$id': typeof V1OperationsIdRouteWithChildren
  '/v1/state/history': typeof V1StateHistoryRoute
  '/v1/document-uploads/': typeof V1DocumentUploadsIndexRoute
  '/v1/documents/': typeof V1DocumentsIndexRoute
  '/v1/entities/': typeof V1EntitiesIndexRoute
  '/v1/events/': typeof V1EventsIndexRoute
  '/v1/memories/': typeof V1MemoriesIndexRoute
  '/v1/operations/': typeof V1OperationsIndexRoute
  '/v1/state/': typeof V1StateIndexRoute
  '/v1/document-uploads/$id/complete': typeof V1DocumentUploadsIdCompleteRoute
  '/v1/document-uploads/$id/content': typeof V1DocumentUploadsIdContentRoute
  '/v1/documents/$id/content': typeof V1DocumentsIdContentRoute
  '/v1/entities/$type/$id': typeof V1EntitiesTypeIdRoute
  '/v1/memories/$id/feedback': typeof V1MemoriesIdFeedbackRoute
  '/v1/memories/$id/history': typeof V1MemoriesIdHistoryRoute
  '/v1/operations/$id/retry': typeof V1OperationsIdRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/magic-link'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/api-keys'
    | '/dashboard/configuration'
    | '/dashboard/create-api'
    | '/dashboard/entities'
    | '/dashboard/memories'
    | '/dashboard/operations'
    | '/dashboard/playground'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/webhooks'
    | '/invite/$token'
    | '/v1/beliefs'
    | '/v1/exports'
    | '/v1/health'
    | '/v1/imports'
    | '/v1/openapi.json'
    | '/v1/profile'
    | '/dashboard/'
    | '/api/app/$'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/cron/tasks'
    | '/api/github-auth/start'
    | '/api/google-auth/start'
    | '/dashboard/entities/$id'
    | '/v1/document-uploads/$id'
    | '/v1/documents/$id'
    | '/v1/documents/search'
    | '/v1/events/$id'
    | '/v1/memories/$id'
    | '/v1/memories/batch'
    | '/v1/memories/search'
    | '/v1/operations/$id'
    | '/v1/state/history'
    | '/v1/document-uploads/'
    | '/v1/documents/'
    | '/v1/entities/'
    | '/v1/events/'
    | '/v1/memories/'
    | '/v1/operations/'
    | '/v1/state/'
    | '/v1/document-uploads/$id/complete'
    | '/v1/document-uploads/$id/content'
    | '/v1/documents/$id/content'
    | '/v1/entities/$type/$id'
    | '/v1/memories/$id/feedback'
    | '/v1/memories/$id/history'
    | '/v1/operations/$id/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/magic-link'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/api-keys'
    | '/dashboard/configuration'
    | '/dashboard/create-api'
    | '/dashboard/entities'
    | '/dashboard/memories'
    | '/dashboard/operations'
    | '/dashboard/playground'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/webhooks'
    | '/invite/$token'
    | '/v1/beliefs'
    | '/v1/exports'
    | '/v1/health'
    | '/v1/imports'
    | '/v1/openapi.json'
    | '/v1/profile'
    | '/dashboard'
    | '/api/app/$'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/cron/tasks'
    | '/api/github-auth/start'
    | '/api/google-auth/start'
    | '/dashboard/entities/$id'
    | '/v1/document-uploads/$id'
    | '/v1/documents/$id'
    | '/v1/documents/search'
    | '/v1/events/$id'
    | '/v1/memories/$id'
    | '/v1/memories/batch'
    | '/v1/memories/search'
    | '/v1/operations/$id'
    | '/v1/state/history'
    | '/v1/document-uploads'
    | '/v1/documents'
    | '/v1/entities'
    | '/v1/events'
    | '/v1/memories'
    | '/v1/operations'
    | '/v1/state'
    | '/v1/document-uploads/$id/complete'
    | '/v1/document-uploads/$id/content'
    | '/v1/documents/$id/content'
    | '/v1/entities/$type/$id'
    | '/v1/memories/$id/feedback'
    | '/v1/memories/$id/history'
    | '/v1/operations/$id/retry'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/magic-link'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/setup'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/api-keys'
    | '/dashboard/configuration'
    | '/dashboard/create-api'
    | '/dashboard/entities'
    | '/dashboard/memories'
    | '/dashboard/operations'
    | '/dashboard/playground'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/webhooks'
    | '/invite/$token'
    | '/v1/beliefs'
    | '/v1/exports'
    | '/v1/health'
    | '/v1/imports'
    | '/v1/openapi.json'
    | '/v1/profile'
    | '/dashboard/'
    | '/api/app/$'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/cron/tasks'
    | '/api/github-auth/start'
    | '/api/google-auth/start'
    | '/dashboard/entities/$id'
    | '/v1/document-uploads/$id'
    | '/v1/documents/$id'
    | '/v1/documents/search'
    | '/v1/events/$id'
    | '/v1/memories/$id'
    | '/v1/memories/batch'
    | '/v1/memories/search'
    | '/v1/operations/$id'
    | '/v1/state/history'
    | '/v1/document-uploads/'
    | '/v1/documents/'
    | '/v1/entities/'
    | '/v1/events/'
    | '/v1/memories/'
    | '/v1/operations/'
    | '/v1/state/'
    | '/v1/document-uploads/$id/complete'
    | '/v1/document-uploads/$id/content'
    | '/v1/documents/$id/content'
    | '/v1/entities/$type/$id'
    | '/v1/memories/$id/feedback'
    | '/v1/memories/$id/history'
    | '/v1/operations/$id/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  V1BeliefsRoute: typeof V1BeliefsRoute
  V1ExportsRoute: typeof V1ExportsRoute
  V1HealthRoute: typeof V1HealthRoute
  V1ImportsRoute: typeof V1ImportsRoute
  V1OpenapiDotjsonRoute: typeof V1OpenapiDotjsonRoute
  V1ProfileRoute: typeof V1ProfileRoute
  ApiAppSplatRoute: typeof ApiAppSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMaintenanceRoute: typeof ApiCronMaintenanceRoute
  ApiCronTasksRoute: typeof ApiCronTasksRoute
  ApiGithubAuthStartRoute: typeof ApiGithubAuthStartRoute
  ApiGoogleAuthStartRoute: typeof ApiGoogleAuthStartRoute
  V1DocumentUploadsIdRoute: typeof V1DocumentUploadsIdRouteWithChildren
  V1DocumentsIdRoute: typeof V1DocumentsIdRouteWithChildren
  V1DocumentsSearchRoute: typeof V1DocumentsSearchRoute
  V1EventsIdRoute: typeof V1EventsIdRoute
  V1MemoriesIdRoute: typeof V1MemoriesIdRouteWithChildren
  V1MemoriesBatchRoute: typeof V1MemoriesBatchRoute
  V1MemoriesSearchRoute: typeof V1MemoriesSearchRoute
  V1OperationsIdRoute: typeof V1OperationsIdRouteWithChildren
  V1StateHistoryRoute: typeof V1StateHistoryRoute
  V1DocumentUploadsIndexRoute: typeof V1DocumentUploadsIndexRoute
  V1DocumentsIndexRoute: typeof V1DocumentsIndexRoute
  V1EntitiesIndexRoute: typeof V1EntitiesIndexRoute
  V1EventsIndexRoute: typeof V1EventsIndexRoute
  V1MemoriesIndexRoute: typeof V1MemoriesIndexRoute
  V1OperationsIndexRoute: typeof V1OperationsIndexRoute
  V1StateIndexRoute: typeof V1StateIndexRoute
  V1EntitiesTypeIdRoute: typeof V1EntitiesTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/profile': {
      id: '/v1/profile'
      path: '/v1/profile'
      fullPath: '/v1/profile'
      preLoaderRoute: typeof V1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/openapi.json': {
      id: '/v1/openapi.json'
      path: '/v1/openapi.json'
      fullPath: '/v1/openapi.json'
      preLoaderRoute: typeof V1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/imports': {
      id: '/v1/imports'
      path: '/v1/imports'
      fullPath: '/v1/imports'
      preLoaderRoute: typeof V1ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/health': {
      id: '/v1/health'
      path: '/v1/health'
      fullPath: '/v1/health'
      preLoaderRoute: typeof V1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/exports': {
      id: '/v1/exports'
      path: '/v1/exports'
      fullPath: '/v1/exports'
      preLoaderRoute: typeof V1ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/beliefs': {
      id: '/v1/beliefs'
      path: '/v1/beliefs'
      fullPath: '/v1/beliefs'
      preLoaderRoute: typeof V1BeliefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources': {
      id: '/dashboard/sources'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations': {
      id: '/dashboard/operations'
      path: '/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memories': {
      id: '/dashboard/memories'
      path: '/memories'
      fullPath: '/dashboard/memories'
      preLoaderRoute: typeof DashboardMemoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/entities': {
      id: '/dashboard/entities'
      path: '/entities'
      fullPath: '/dashboard/entities'
      preLoaderRoute: typeof DashboardEntitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-api': {
      id: '/dashboard/create-api'
      path: '/create-api'
      fullPath: '/dashboard/create-api'
      preLoaderRoute: typeof DashboardCreateApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuration': {
      id: '/dashboard/configuration'
      path: '/configuration'
      fullPath: '/dashboard/configuration'
      preLoaderRoute: typeof DashboardConfigurationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v1/state/': {
      id: '/v1/state/'
      path: '/v1/state'
      fullPath: '/v1/state/'
      preLoaderRoute: typeof V1StateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/operations/': {
      id: '/v1/operations/'
      path: '/v1/operations'
      fullPath: '/v1/operations/'
      preLoaderRoute: typeof V1OperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memories/': {
      id: '/v1/memories/'
      path: '/v1/memories'
      fullPath: '/v1/memories/'
      preLoaderRoute: typeof V1MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/events/': {
      id: '/v1/events/'
      path: '/v1/events'
      fullPath: '/v1/events/'
      preLoaderRoute: typeof V1EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/entities/': {
      id: '/v1/entities/'
      path: '/v1/entities'
      fullPath: '/v1/entities/'
      preLoaderRoute: typeof V1EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/documents/': {
      id: '/v1/documents/'
      path: '/v1/documents'
      fullPath: '/v1/documents/'
      preLoaderRoute: typeof V1DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/document-uploads/': {
      id: '/v1/document-uploads/'
      path: '/v1/document-uploads'
      fullPath: '/v1/document-uploads/'
      preLoaderRoute: typeof V1DocumentUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/state/history': {
      id: '/v1/state/history'
      path: '/v1/state/history'
      fullPath: '/v1/state/history'
      preLoaderRoute: typeof V1StateHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/operations/$id': {
      id: '/v1/operations/$id'
      path: '/v1/operations/$id'
      fullPath: '/v1/operations/$id'
      preLoaderRoute: typeof V1OperationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memories/search': {
      id: '/v1/memories/search'
      path: '/v1/memories/search'
      fullPath: '/v1/memories/search'
      preLoaderRoute: typeof V1MemoriesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memories/batch': {
      id: '/v1/memories/batch'
      path: '/v1/memories/batch'
      fullPath: '/v1/memories/batch'
      preLoaderRoute: typeof V1MemoriesBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memories/$id': {
      id: '/v1/memories/$id'
      path: '/v1/memories/$id'
      fullPath: '/v1/memories/$id'
      preLoaderRoute: typeof V1MemoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/events/$id': {
      id: '/v1/events/$id'
      path: '/v1/events/$id'
      fullPath: '/v1/events/$id'
      preLoaderRoute: typeof V1EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/documents/search': {
      id: '/v1/documents/search'
      path: '/v1/documents/search'
      fullPath: '/v1/documents/search'
      preLoaderRoute: typeof V1DocumentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/documents/$id': {
      id: '/v1/documents/$id'
      path: '/v1/documents/$id'
      fullPath: '/v1/documents/$id'
      preLoaderRoute: typeof V1DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/document-uploads/$id': {
      id: '/v1/document-uploads/$id'
      path: '/v1/document-uploads/$id'
      fullPath: '/v1/document-uploads/$id'
      preLoaderRoute: typeof V1DocumentUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/entities/$id': {
      id: '/dashboard/entities/$id'
      path: '/$id'
      fullPath: '/dashboard/entities/$id'
      preLoaderRoute: typeof DashboardEntitiesIdRouteImport
      parentRoute: typeof DashboardEntitiesRoute
    }
    '/api/google-auth/start': {
      id: '/api/google-auth/start'
      path: '/api/google-auth/start'
      fullPath: '/api/google-auth/start'
      preLoaderRoute: typeof ApiGoogleAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-auth/start': {
      id: '/api/github-auth/start'
      path: '/api/github-auth/start'
      fullPath: '/api/github-auth/start'
      preLoaderRoute: typeof ApiGithubAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tasks': {
      id: '/api/cron/tasks'
      path: '/api/cron/tasks'
      fullPath: '/api/cron/tasks'
      preLoaderRoute: typeof ApiCronTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/maintenance': {
      id: '/api/cron/maintenance'
      path: '/api/cron/maintenance'
      fullPath: '/api/cron/maintenance'
      preLoaderRoute: typeof ApiCronMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app/$': {
      id: '/api/app/$'
      path: '/api/app/$'
      fullPath: '/api/app/$'
      preLoaderRoute: typeof ApiAppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/operations/$id/retry': {
      id: '/v1/operations/$id/retry'
      path: '/retry'
      fullPath: '/v1/operations/$id/retry'
      preLoaderRoute: typeof V1OperationsIdRetryRouteImport
      parentRoute: typeof V1OperationsIdRoute
    }
    '/v1/memories/$id/history': {
      id: '/v1/memories/$id/history'
      path: '/history'
      fullPath: '/v1/memories/$id/history'
      preLoaderRoute: typeof V1MemoriesIdHistoryRouteImport
      parentRoute: typeof V1MemoriesIdRoute
    }
    '/v1/memories/$id/feedback': {
      id: '/v1/memories/$id/feedback'
      path: '/feedback'
      fullPath: '/v1/memories/$id/feedback'
      preLoaderRoute: typeof V1MemoriesIdFeedbackRouteImport
      parentRoute: typeof V1MemoriesIdRoute
    }
    '/v1/entities/$type/$id': {
      id: '/v1/entities/$type/$id'
      path: '/v1/entities/$type/$id'
      fullPath: '/v1/entities/$type/$id'
      preLoaderRoute: typeof V1EntitiesTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/documents/$id/content': {
      id: '/v1/documents/$id/content'
      path: '/content'
      fullPath: '/v1/documents/$id/content'
      preLoaderRoute: typeof V1DocumentsIdContentRouteImport
      parentRoute: typeof V1DocumentsIdRoute
    }
    '/v1/document-uploads/$id/content': {
      id: '/v1/document-uploads/$id/content'
      path: '/content'
      fullPath: '/v1/document-uploads/$id/content'
      preLoaderRoute: typeof V1DocumentUploadsIdContentRouteImport
      parentRoute: typeof V1DocumentUploadsIdRoute
    }
    '/v1/document-uploads/$id/complete': {
      id: '/v1/document-uploads/$id/complete'
      path: '/complete'
      fullPath: '/v1/document-uploads/$id/complete'
      preLoaderRoute: typeof V1DocumentUploadsIdCompleteRouteImport
      parentRoute: typeof V1DocumentUploadsIdRoute
    }
  }
}

interface DashboardEntitiesRouteChildren {
  DashboardEntitiesIdRoute: typeof DashboardEntitiesIdRoute
}

const DashboardEntitiesRouteChildren: DashboardEntitiesRouteChildren = {
  DashboardEntitiesIdRoute: DashboardEntitiesIdRoute,
}

const DashboardEntitiesRouteWithChildren =
  DashboardEntitiesRoute._addFileChildren(DashboardEntitiesRouteChildren)

interface DashboardRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardConfigurationRoute: typeof DashboardConfigurationRoute
  DashboardCreateApiRoute: typeof DashboardCreateApiRoute
  DashboardEntitiesRoute: typeof DashboardEntitiesRouteWithChildren
  DashboardMemoriesRoute: typeof DashboardMemoriesRoute
  DashboardOperationsRoute: typeof DashboardOperationsRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSourcesRoute: typeof DashboardSourcesRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardConfigurationRoute: DashboardConfigurationRoute,
  DashboardCreateApiRoute: DashboardCreateApiRoute,
  DashboardEntitiesRoute: DashboardEntitiesRouteWithChildren,
  DashboardMemoriesRoute: DashboardMemoriesRoute,
  DashboardOperationsRoute: DashboardOperationsRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface V1DocumentUploadsIdRouteChildren {
  V1DocumentUploadsIdCompleteRoute: typeof V1DocumentUploadsIdCompleteRoute
  V1DocumentUploadsIdContentRoute: typeof V1DocumentUploadsIdContentRoute
}

const V1DocumentUploadsIdRouteChildren: V1DocumentUploadsIdRouteChildren = {
  V1DocumentUploadsIdCompleteRoute: V1DocumentUploadsIdCompleteRoute,
  V1DocumentUploadsIdContentRoute: V1DocumentUploadsIdContentRoute,
}

const V1DocumentUploadsIdRouteWithChildren =
  V1DocumentUploadsIdRoute._addFileChildren(V1DocumentUploadsIdRouteChildren)

interface V1DocumentsIdRouteChildren {
  V1DocumentsIdContentRoute: typeof V1DocumentsIdContentRoute
}

const V1DocumentsIdRouteChildren: V1DocumentsIdRouteChildren = {
  V1DocumentsIdContentRoute: V1DocumentsIdContentRoute,
}

const V1DocumentsIdRouteWithChildren = V1DocumentsIdRoute._addFileChildren(
  V1DocumentsIdRouteChildren,
)

interface V1MemoriesIdRouteChildren {
  V1MemoriesIdFeedbackRoute: typeof V1MemoriesIdFeedbackRoute
  V1MemoriesIdHistoryRoute: typeof V1MemoriesIdHistoryRoute
}

const V1MemoriesIdRouteChildren: V1MemoriesIdRouteChildren = {
  V1MemoriesIdFeedbackRoute: V1MemoriesIdFeedbackRoute,
  V1MemoriesIdHistoryRoute: V1MemoriesIdHistoryRoute,
}

const V1MemoriesIdRouteWithChildren = V1MemoriesIdRoute._addFileChildren(
  V1MemoriesIdRouteChildren,
)

interface V1OperationsIdRouteChildren {
  V1OperationsIdRetryRoute: typeof V1OperationsIdRetryRoute
}

const V1OperationsIdRouteChildren: V1OperationsIdRouteChildren = {
  V1OperationsIdRetryRoute: V1OperationsIdRetryRoute,
}

const V1OperationsIdRouteWithChildren = V1OperationsIdRoute._addFileChildren(
  V1OperationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  V1BeliefsRoute: V1BeliefsRoute,
  V1ExportsRoute: V1ExportsRoute,
  V1HealthRoute: V1HealthRoute,
  V1ImportsRoute: V1ImportsRoute,
  V1OpenapiDotjsonRoute: V1OpenapiDotjsonRoute,
  V1ProfileRoute: V1ProfileRoute,
  ApiAppSplatRoute: ApiAppSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMaintenanceRoute: ApiCronMaintenanceRoute,
  ApiCronTasksRoute: ApiCronTasksRoute,
  ApiGithubAuthStartRoute: ApiGithubAuthStartRoute,
  ApiGoogleAuthStartRoute: ApiGoogleAuthStartRoute,
  V1DocumentUploadsIdRoute: V1DocumentUploadsIdRouteWithChildren,
  V1DocumentsIdRoute: V1DocumentsIdRouteWithChildren,
  V1DocumentsSearchRoute: V1DocumentsSearchRoute,
  V1EventsIdRoute: V1EventsIdRoute,
  V1MemoriesIdRoute: V1MemoriesIdRouteWithChildren,
  V1MemoriesBatchRoute: V1MemoriesBatchRoute,
  V1MemoriesSearchRoute: V1MemoriesSearchRoute,
  V1OperationsIdRoute: V1OperationsIdRouteWithChildren,
  V1StateHistoryRoute: V1StateHistoryRoute,
  V1DocumentUploadsIndexRoute: V1DocumentUploadsIndexRoute,
  V1DocumentsIndexRoute: V1DocumentsIndexRoute,
  V1EntitiesIndexRoute: V1EntitiesIndexRoute,
  V1EventsIndexRoute: V1EventsIndexRoute,
  V1MemoriesIndexRoute: V1MemoriesIndexRoute,
  V1OperationsIndexRoute: V1OperationsIndexRoute,
  V1StateIndexRoute: V1StateIndexRoute,
  V1EntitiesTypeIdRoute: V1EntitiesTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
